import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/> {/* Sayfa başlığı için Header bileşenini çağırıyoruz. */}
        {children}
        <Footer/> {/* Sayfa alt kısmı için Footer bileşenini çağırıyoruz. */}

        </body>
    </html>
  );
}
